### ISSUE TITLE
Unter Curriculum, WI, Management funktionieren die Links zu den oberen beiden MOOCs nicht, da diese nicht mehr existieren. @jessilenwell könnt ihr da neue raussuchen und evtl. neue Texte dazu verfassen?

### ISSUE THREAD

**Issue by jessilenwell** [imbitdhbwma/brillianplatform#36]
Unter Curriculum, WI, Management funktionieren die Links zu den oberen beiden MOOCs nicht, da diese nicht mehr existieren. @jessilenwell könnt ihr da neue raussuchen und evtl. neue Texte dazu verfassen?
![Anmerkung 2019-10-26 183340](https://user-images.githubusercontent.com/56722107/67622968-f0415980-f81f-11e9-802d-9580c9bd3e6c.png)
![Uploading Anmerkung 2019-10-26 183423.png…]()

_Originally posted by @LauraBrinks in https://github.com/imbitdhbwma/brillianplatform/issues/21#issuecomment-546618994_

28.10 
Links wurden rausgesucht und werden jetzt in der Gruppe, auf Nutzen analysiert

**Comment by juliaschmatolla** [comment]
Beispiel Links für MOCC´s:

**Happiness at work** - https://www.edx.org/course/the-foundations-of-happiness-at-work

**Human Resource Management: HR for People Managers Specialization** - Do you have people reporting to you that need managing? Or perhaps you want to consider a career in human resources? Or freshen up your HR knowledge?
https://www.coursera.org/specializations/human-resource-management?ranMID=40328&ranEAID=*GqSdLGGurk&ranSiteID=.GqSdLGGurk-v1Jv1857coTxkLfxVxScjQ&siteID=.GqSdLGGurk-v1Jv1857coTxkLfxVxScjQ&utm_content=10&utm_medium=partners&utm_source=linkshare&utm_campaign=*GqSdLGGurk



**Entrepreneurship:** Wharton's Entrepreneurship Specialization covers the conception, design, organization, and management of new enterprises. This five-course series is designed to take you from opportunity identification through launch, growth, financing and profitability. -
https://www.coursera.org/specializations/wharton-entrepreneurship


**Entrepreneurship Strategy: From Ideation to Exit** - This course covers in the chronological order each defining step of an entrepreneurial project. It begins with very personal considerations related to getting to better know yourself better so as to decide if you are ready for the multiple challenges of entrepreneurship. It then deals with creativity in order to provide the right set of tools to find an idea with the right potential to disrupt an existing business.
https://www.coursera.org/learn/entrepreneurship-strategy


**Job Success: Get Hired or Promoted in 3 Steps** - This course, Job Success: Get Hired or Promoted in Three Steps, will prepare you to stand out in a crowded applicant pool so that you can get hired or promoted.
https://www.coursera.org/learn/get-hired

**Business Analytics Specialization** - This Specialization provides an introduction to big data analytics for all business professionals, including those with no prior analytics experience. You’ll learn how data analysts describe, predict, and inform business decisions in the specific areas of marketing, human resources, finance, and operations, and you’ll develop basic data literacy and an analytic mindset that will help you make strategic decisions based on data.
https://www.coursera.org/specializations/business-analytics

**Comment by juliaschmatolla** [comment]
Rückmeldung noch ausstehend

**Comment by juliaschmatolla** [comment]
HR: Bitte MOOC 1
Entrepreneurship: Bitte MOOC 4
HR Management: Bitte MOOC 2

**Comment by juliaschmatolla** [comment]
@JulianeOrt Implementierungs-Issue ist noch in progress da getestet werden muss
